ALTER TABLE `conversation_creature`   
  ADD COLUMN `unk1` INT(11) UNSIGNED DEFAULT 0  NOT NULL AFTER `creatureGuid`,
  ADD COLUMN `unk2` INT(11) UNSIGNED DEFAULT 0  NOT NULL AFTER `unk1`,
  ADD COLUMN `duration` INT(11) UNSIGNED DEFAULT 0  NOT NULL AFTER `unk2`;

  CREATE TABLE `conversation_actor` (
  `entry` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `actorId` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `creatureId` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `displayId` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `unk1` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `unk2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `unk3` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `duration` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`,`id`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
