ALTER TABLE `trinworld701`.`creature_equip_template`   
  ADD COLUMN `ItemID2` INT(11) UNSIGNED DEFAULT 0  NOT NULL AFTER `ItemID1`,
  CHANGE `ItemID2` `ItemID3` INT(11) UNSIGNED DEFAULT 0  NOT NULL,
  ADD COLUMN `ItemID4` INT(11) UNSIGNED DEFAULT 0  NOT NULL AFTER `ItemID3`,
  CHANGE `ItemID3` `ItemID5` INT(11) UNSIGNED DEFAULT 0  NOT NULL,
  ADD COLUMN `ItemID6` INT(11) UNSIGNED DEFAULT 0  NOT NULL AFTER `ItemID5`;
