ALTER TABLE `creature`   
  ADD COLUMN `AiID` INT(10) UNSIGNED DEFAULT 0  NOT NULL AFTER `dynamicflags`,
  ADD COLUMN `MovementID` INT(10) UNSIGNED DEFAULT 0  NOT NULL AFTER `AiID`,
  ADD COLUMN `MeleeID` INT(10) UNSIGNED DEFAULT 0  NOT NULL AFTER `MovementID`;

ALTER TABLE `creature_template`   
  DROP COLUMN `AiID`, 
  DROP COLUMN `MovementIDKit`, 
  DROP COLUMN `MeleeID`;

