ALTER TABLE `spell_totems`   
  CHANGE `TotemCategory1` `Totem1` INT(10) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `TotemCategory2` `Totem2` INT(10) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `Totem1` `TotemCategory1` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `Totem2` `TotemCategory2` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL;
