CREATE TABLE `character_artifact`(  
  `guid` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `owner` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `Power` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `AppearanceID` MEDIUMINT(6) UNSIGNED NOT NULL DEFAULT 0,
  `Gems` TEXT NOT NULL,
  `Powers` TEXT NOT NULL,
  PRIMARY KEY (`guid`)
);
